use_frameworks!

platform :ios, '11.0'

target 'PlaceholderTextField_Example' do
  pod 'PlaceholderTextField', '~> 0.1.0'

  target 'PlaceholderTextField_Tests' do
    inherit! :search_paths

    
  end
end
