use_frameworks!

platform :ios, '9.0'

target 'PlaceholderTextField_Example' do
  pod 'PlaceholderTextField', :path => '../'

  target 'PlaceholderTextField_Tests' do
    inherit! :search_paths

    
  end
end
